# Generated by Django 5.0.14 on 2025-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('contract', 'Договор'), ('invoice', 'Счет'), ('act', 'Акт')], max_length=50)),
                ('params', models.JSONField(default=dict)),
                ('generated_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('purchase', 'Закупка'), ('marketing', 'Реклама'), ('salary', 'Зарплаты'), ('rent', 'Аренда'), ('tax', 'Налоги'), ('other', 'Другое')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('services', 'Услуги'), ('goods', 'Товары'), ('rent', 'Аренда'), ('other', 'Другое')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
