# Generated by Django 5.0.14 on 2025-11-05 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_uploadedfile_alter_chatsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='encrypted_content',
            field=models.TextField(blank=True, help_text='Зашифрованное содержимое', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Зашифровано ли сообщение'),
        ),
        migrations.AddField(
            model_name='expense',
            name='encrypted_data',
            field=models.TextField(blank=True, help_text='Зашифрованные данные (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Зашифрованы ли данные'),
        ),
        migrations.AddField(
            model_name='income',
            name='encrypted_data',
            field=models.TextField(blank=True, help_text='Зашифрованные данные (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Зашифрованы ли данные'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_phrase', models.TextField(blank=True, help_text='Seed phrase для восстановления ключа (зашифрован)', null=True)),
                ('private_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('encryption_enabled', models.BooleanField(default=True, help_text='Включено ли шифрование')),
                ('local_mode_only', models.BooleanField(default=False, help_text='Использовать только локальные модели (без облака)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
