# Generated by Django 5.0.14 on 2025-11-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatmessage_encrypted_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='analytics_summaries',
            field=models.JSONField(blank=True, default=dict, help_text='Кэш сводных метрик/графиков по сессии'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='data_summaries',
            field=models.JSONField(blank=True, default=dict, help_text='Краткие сводки по файлам и данным, ключи — file_id или logical name'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='chat_sessions', to='core.uploadedfile'),
        ),
    ]
