# Generated by Django 5.0.14 on 2025-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatsession_analytics_summaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_useful',
            field=models.BooleanField(default=False, help_text='Отметка пользователя, что совет оказался полезным'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные метаданные сообщения (советы, действия, флаги)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='action_log',
            field=models.JSONField(blank=True, default=dict, help_text='Лог советов и статусов действий в рамках сессии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='financial_memory',
            field=models.JSONField(blank=True, default=dict, help_text='Глобальная финансовая память пользователя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='success_cases',
            field=models.JSONField(blank=True, default=list, help_text='Истории успешных рекомендаций'),
        ),
    ]
