# Generated by Django 5.0.10 on 2025-11-08 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatmessage_is_useful_chatmessage_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='Файл, из которого была импортирована эта транзакция', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.uploadedfile'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='Файл, из которого была импортирована эта транзакция', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.uploadedfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_clear_file_on_import',
            field=models.BooleanField(default=False, help_text='Автоматически удалять все транзакции из файла при повторной загрузке'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_remove_duplicates',
            field=models.BooleanField(default=False, help_text='Автоматически удалять дублирующиеся строки при импорте'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_file', 'date', 'amount', 'category'], name='core_expens_source__d7db75_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['source_file', 'date', 'amount', 'category'], name='core_income_source__8d004d_idx'),
        ),
    ]
